version: '3.1'

services:
  nest-postgresql:
    image: postgres:9.6.23
    restart: always
    container_name: nest-postgresql
    environment:
      - POSTGRES_DB=post
      - POSTGRES_USER=postuser
      - POSTGRES_PASSWORD=9999
    ports:
      - 5433:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
